name: despesas

services:
    database:
      image: postgres:11.13-alpine
      container_name: despesas-database
      environment:
        POSTGRES_USER: despesas
        POSTGRES_PASSWORD: despesas_db
        POSTGRES_DB: despesas
      ports:
        - "5432:5432"

    app:
      image: leokaos/despesas:${DESPESAS_VERSION}
      container_name: despesas-app
      volumes: 
        - /despesas-index:/opt/jboss/despesas_index

    ia:
      image: leokaos/despesas-ia:${DESPESAS_IA_VERSION}
      container_name: despesas-ia