CREATE TABLE despesas_db.META (
	ID BIGINT NOT NULL,
	MES INT NOT NULL,
	ANO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE despesas_db.meta_id_seq START 1;

