CREATE TABLE despesas_db.INVESTIMENTO (
	MONTANTE NUMERIC(19,2) NOT NULL, 
	ID BIGINT NOT NULL,
	PERIODICIDADE VARCHAR(255) NOT NULL,
	RENDIMENTO NUMERIC(19,2) NOT NULL, 
	PRIMARY KEY(ID)
);

ALTER TABLE despesas_db.INVESTIMENTO ADD CONSTRAINT INVESTIMENTO_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
ALTER TABLE despesas_db.RECEITA ADD COLUMN INVESTIMENTO_ID BIGINT NULL;

ALTER TABLE despesas_db.RECEITA ADD CONSTRAINT INVESTIMENTO_RECEITA_FK 
	FOREIGN KEY (INVESTIMENTO_ID) REFERENCES despesas_db.INVESTIMENTO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
