CREATE TABLE despesas_db.DIVIDA (
	VALOR_TOTAL NUMERIC(19,2) NOT NULL,
	PERIODICIODADE VARCHAR(255) NOT NULL,
	DATA_INICIO TIMESTAMP NOT NULL,
	ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);


ALTER TABLE despesas_db.DIVIDA ADD CONSTRAINT DIVIDA_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;