
CREATE TABLE TIPO_MOVIMENTACAO (
	TIPO VARCHAR(31) NOT NULL, 
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	COR VARCHAR(255) NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE CARTAO (
	BANDEIRACARTAOCREDITO VARCHAR(255) NOT NULL, 
	DIADEFECHAMENTO INTEGER NOT NULL, 
	DIADEVENCIMENTO INTEGER NOT NULL, 
	LIMITE NUMERIC(19,2) NOT NULL, 
	ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE CONTA (
	SALDO NUMERIC(19,2) NOT NULL, 
	ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE DEBITAVEL (
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	COR VARCHAR(255) NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE MOVIMENTACAO (
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	DESCRICAO VARCHAR(255) NOT NULL, 
	PAGAMENTO TIMESTAMP, 
	VALOR NUMERIC(19,2) NOT NULL, 
	VENCIMENTO TIMESTAMP NOT NULL, 
	DEBITAVEL_ID BIGINT,
	TIPO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE DESPESA (
	PAGA BOOLEAN NOT NULL, 
	ID BIGINT NOT NULL, 
	TIPO_DESPESA_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE CONTA ADD CONSTRAINT CONTA_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MOVIMENTACAO ADD CONSTRAINT MOVIMENTACAO_DEBITAVEL_FK 
	FOREIGN KEY (DEBITAVEL_ID) REFERENCES DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CARTAO ADD CONSTRAINT CARTAO_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE DESPESA ADD CONSTRAINT DESPESA_MOVIMENTACAO_FK 
	FOREIGN KEY (ID) REFERENCES MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE DESPESA ADD CONSTRAINT DESPESA_TIPO_MOVIMENTACAO_FK 
	FOREIGN KEY (TIPO_DESPESA_ID) REFERENCES TIPO_MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
