
CREATE DATABASE despesas_db;

CREATE SCHEMA despesas_db;

CREATE TABLE despesas_db.TIPO_MOVIMENTACAO (
	ID BIGINT NOT NULL, 
	COR VARCHAR(255) NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL,
	TIPO varchar(255);
	PRIMARY KEY(ID)
);

CREATE TABLE despesas_db.CARTAO (
	BANDEIRACARTAOCREDITO VARCHAR(255) NOT NULL, 
	DIADEFECHAMENTO INTEGER NOT NULL, 
	DIADEVENCIMENTO INTEGER NOT NULL, 
	LIMITE NUMERIC(19,2) NOT NULL, 
	ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE despesas_db.CONTA (
	SALDO NUMERIC(19,2) NOT NULL, 
	ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE despesas_db.DEBITAVEL (
	ID BIGINT NOT NULL, 
	COR VARCHAR(255) NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE despesas_db.MOVIMENTACAO (
	ID BIGINT NOT NULL, 
	DESCRICAO VARCHAR(255) NOT NULL, 
	PAGAMENTO TIMESTAMP, 
	VALOR NUMERIC(19,2) NOT NULL, 
	VENCIMENTO TIMESTAMP NOT NULL, 
	DEBITAVEL_ID BIGINT,
	PRIMARY KEY(ID)
);

CREATE TABLE despesas_db.DESPESA (
	PAGA BOOLEAN NOT NULL, 
	ID BIGINT NOT NULL, 
	TIPO_DESPESA_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE despesas_db.CONTA ADD CONSTRAINT CONTA_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE despesas_db.MOVIMENTACAO ADD CONSTRAINT MOVIMENTACAO_DEBITAVEL_FK 
	FOREIGN KEY (DEBITAVEL_ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE despesas_db.CARTAO ADD CONSTRAINT CARTAO_DEBITAVEL_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE despesas_db.DESPESA ADD CONSTRAINT DESPESA_MOVIMENTACAO_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE despesas_db.DESPESA ADD CONSTRAINT DESPESA_TIPO_MOVIMENTACAO_FK 
	FOREIGN KEY (TIPO_DESPESA_ID) REFERENCES despesas_db.TIPO_MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
CREATE SEQUENCE despesas_db.movimentacao_id_seq START 1;

CREATE SEQUENCE despesas_db.tipo_movimentacao_id_seq START 1;

CREATE SEQUENCE despesas_db.fatura_id_seq START 1;

CREATE SEQUENCE despesas_db.debitavel_id_seq START 1;
