create schema despesas_db;

CREATE TABLE despesas_db.tipo_despesa(

	id bigint GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255),
	cor varchar(50),
	primary key(id)
);

CREATE TABLE despesas_db.conta(

	id bigint GENERATED BY DEFAULT AS IDENTITY,
	cor varchar(255),
	nome varchar(50),
	saldo numeric(19,2),
	primary key(id)
);

CREATE TABLE despesas_db.movimentacao(
	
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255),
	valor numeric(19,2),
	vencimento TIMESTAMP,
	pagamento TIMESTAMP,
	conta_id bigint,
	tipo varchar(1),
	primary key(id)
);

ALTER TABLE despesas_db.movimentacao ADD FOREIGN KEY (conta_id) REFERENCES despesas_db.conta(id);

CREATE TABLE despesas_db.despesa(
	
	id bigint,
	paga boolean,
	tipo_despesa_id bigint,
	primary key(id)
);

ALTER TABLE despesas_db.despesa ADD FOREIGN KEY (tipo_despesa_id) REFERENCES despesas_db.tipo_despesa(id);