CREATE TABLE ORCAMENTO (

        ID BIGINT NOT NULL AUTO_INCREMENT,
        TIPO_DESPESA_ID BIGINT NOT NULL,
        VALOR NUMERIC(10,2) NOT NULL,
        DATA_INICIAL TIMESTAMP NOT NULL,
        DATA_FINAL TIMESTAMP NOT NULL,
        PRIMARY KEY(ID)
);

ALTER TABLE ORCAMENTO ADD CONSTRAINT ORCAMENTO_TIPO_DESPESA FOREIGN KEY (TIPO_DESPESA_ID) REFERENCES TIPO_MOVIMENTACAO(ID)
 ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE FATURA (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        CARTAO_ID BIGINT NOT NULL,
        DATA_VENCIMENTO TIMESTAMP NOT NULL,
        DATA_FECHAMENTO TIMESTAMP NOT NULL,
        PRIMARY KEY(ID)
);

ALTER TABLE FATURA ADD CONSTRAINT FATURA_CARTAO FOREIGN KEY (CARTAO_ID) REFERENCES CARTAO(ID)
 ON DELETE NO ACTION ON UPDATE NO ACTION;
 
ALTER TABLE DESPESA ADD COLUMN FATURA_ID BIGINT;

ALTER TABLE DESPESA ADD CONSTRAINT DESPESA_FATURA FOREIGN KEY (FATURA_ID) REFERENCES FATURA(ID)
 ON DELETE NO ACTION ON UPDATE NO ACTION;