CREATE TABLE RECEITA (
	DEPOSITADO BOOLEAN NOT NULL, 
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	TIPO_RECEITA_ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE RECEITA ADD CONSTRAINT RECEITA_MOVIMENTACAO_FK 
	FOREIGN KEY (ID) REFERENCES MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
ALTER TABLE RECEITA ADD CONSTRAINT RECEITA_TIPO_MOVIMENTACAO_FK 
	FOREIGN KEY (TIPO_RECEITA_ID) REFERENCES TIPO_MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;