ALTER TABLE "DESPESAS_DB"."CARTAO" ADD COLUMN "LIMITE_ATUAL" NUMERIC(19,2);
UPDATE "DESPESAS_DB"."CARTAO" SET LIMITE_ATUAL = LIMITE;

ALTER TABLE "DESPESAS_DB"."FATURA" ADD COLUMN "PAGA" BOOLEAN DEFAULT FALSE;