CREATE TABLE "DESPESAS_DB"."TRANSFERENCIA" (
	"ID" BIGINT NOT NULL,
	"CREDITAVEL_ID" BIGINT NOT NULL
);

ALTER TABLE "DESPESAS_DB"."TRANSFERENCIA" ADD CONSTRAINT "TRANSFERENCIA_PK" PRIMARY KEY ("ID");

ALTER TABLE "DESPESAS_DB"."TRANSFERENCIA" ADD CONSTRAINT "TRANSFERENCIA_MOVIMENTACAO_FK" 
	FOREIGN KEY ("ID") REFERENCES "DESPESAS_DB"."MOVIMENTACAO" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
	
ALTER TABLE "DESPESAS_DB"."TRANSFERENCIA" ADD CONSTRAINT "TRANSFERENCIA_DEBITAVEL_FK" 
	FOREIGN KEY ("CREDITAVEL_ID") REFERENCES "DESPESAS_DB"."DEBITAVEL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;