CREATE TABLE TRANSFERENCIA (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CREDITAVEL_ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE TRANSFERENCIA ADD CONSTRAINT TRANSFERENCIA_MOVIMENTACAO_FK 
	FOREIGN KEY (ID) REFERENCES MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
ALTER TABLE TRANSFERENCIA ADD CONSTRAINT TRANSFERENCIA_DEBITAVEL_FK 
	FOREIGN KEY (CREDITAVEL_ID) REFERENCES DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;