CREATE TABLE despesas_db.TRANSFERENCIA (
	ID BIGINT NOT NULL,
	CREDITAVEL_ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE despesas_db.TRANSFERENCIA ADD CONSTRAINT TRANSFERENCIA_MOVIMENTACAO_FK 
	FOREIGN KEY (ID) REFERENCES despesas_db.MOVIMENTACAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
	
ALTER TABLE despesas_db.TRANSFERENCIA ADD CONSTRAINT TRANSFERENCIA_DEBITAVEL_FK 
	FOREIGN KEY (CREDITAVEL_ID) REFERENCES despesas_db.DEBITAVEL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;