CREATE TABLE despesas_db.SERVICO_TRANSFERENCIA (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TAXAS NUMERIC(19,2) not null,
	SPRED NUMERIC(19,2) not null,
	NOME varchar(255) not null,
	PRIMARY KEY (ID)
);

DROP TABLE despesas_db.SERVICO_TRANSFERENCIA;

select * from despesas_db.SERVICO_TRANSFERENCIA;