name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nova versão (ex: 0.16)'
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: '8.0.482+8'
        distribution: 'temurin'
        cache: maven

    - name: Set new version
      run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }}

    - name: Commit version change
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pom.xml */pom.xml */*/pom.xml
        git commit -m "bump version to ${{ github.event.inputs.version }}"
        git push

    - name: Build with Maven
      run: mvn -B package -P prod --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Deploy to Docker Hub
      run: mvn clean deploy

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          /home/leo/server/despesas/deploy.sh ${{ github.event.inputs.version }}